# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fafbcc9231c4ca44887ef9b69added43"
name = "royal-test-1"
handle = "royal-test-1"
application_url = "https://royal-deploy.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "karan-working.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customers,read_orders,read_products,write_checkouts,write_orders,write_products"

[auth]
redirect_urls = [
  "https://royal-deploy.vercel.app/auth/callback",
  "https://royal-deploy.vercel.app/auth/shopify/callback",
  "https://royal-deploy.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://royal-deploy.vercel.app/api/webhooks"

[pos]
embedded = false
